export const INITIAL_GOOGLE_OFFICIAL_SOURCE_REGISTRY = [
  {
    source_id: 'google-search-essentials',
    source_name: 'Google Search Essentials (formerly Webmaster Guidelines)',
    official_domain: 'developers.google.com',
    current_url: 'https://developers.google.com/search/docs/essentials',
    previous_urls: ['https://developers.google.com/search/docs/advanced/guidelines/webmaster-guidelines'],
    source_type: 'SEARCH_ESSENTIALS',
    last_verified_at: new Date().toISOString(),
    http_status: 200,
    redirect_chain: [],
    status: 'ACTIVE',
    notes: 'Core technical, behavioral, and quality requirements for Google Search inclusion.',
    classification: {
      source_id: 'google-search-essentials',
      change_summary: 'Verified core technical, indexing, and quality criteria.',
      supporting_quote: 'Google Search Essentials make up the core parts of what makes your web-based content eligible to show up on Google Search.',
      affects_blog: true,
      affects_review: true,
      affects_structured_data: false,
      confidence: 'high',
      requires_human_review: false
    }
  },
  {
    source_id: 'google-spam-policies',
    source_name: 'Spam Policies for Google Web Search',
    official_domain: 'developers.google.com',
    current_url: 'https://developers.google.com/search/docs/essentials/spam-policies',
    previous_urls: ['https://developers.google.com/search/docs/advanced/guidelines/search-quality-guidelines'],
    source_type: 'SPAM_POLICIES',
    last_verified_at: new Date().toISOString(),
    http_status: 200,
    redirect_chain: [],
    status: 'ACTIVE',
    notes: 'Defines scaled content abuse, expired domain abuse, site reputation abuse, and doorway pages.',
    classification: {
      source_id: 'google-spam-policies',
      change_summary: 'Verified anti-spam rules regarding scaled content abuse, fake reviews, and keyword stuffing.',
      supporting_quote: 'Our spam policies help protect users and improve the quality of search results.',
      affects_blog: true,
      affects_review: true,
      affects_structured_data: false,
      confidence: 'high',
      requires_human_review: false
    }
  },
  {
    source_id: 'google-helpful-content',
    source_name: 'Google Guidance on Creating Helpful, People-First Content',
    official_domain: 'developers.google.com',
    current_url: 'https://developers.google.com/search/docs/fundamentals/creating-helpful-content',
    previous_urls: ['https://developers.google.com/search/blog/2022/08/helpful-content-system'],
    source_type: 'HELPFUL_CONTENT',
    last_verified_at: new Date().toISOString(),
    http_status: 200,
    redirect_chain: [],
    status: 'ACTIVE',
    notes: 'People-first content criteria vs search-engine-first content flags.',
    classification: {
      source_id: 'google-helpful-content',
      change_summary: 'Verified people-first guidance focusing on primary utility for human visitors.',
      supporting_quote: 'Google automated ranking systems are designed to present helpful, reliable information that was created primarily to benefit people.',
      affects_blog: true,
      affects_review: false,
      affects_structured_data: false,
      confidence: 'high',
      requires_human_review: false
    }
  },
  {
    source_id: 'google-ai-content-guidance',
    source_name: 'Google Search Guidance About AI-Generated Content',
    official_domain: 'developers.google.com',
    current_url: 'https://developers.google.com/search/docs/fundamentals/creating-helpful-content#ai-generated-content',
    previous_urls: [],
    source_type: 'AI_GUIDANCE',
    last_verified_at: new Date().toISOString(),
    http_status: 200,
    redirect_chain: [],
    status: 'ACTIVE',
    notes: 'AI content is acceptable if helpful, original, and compliant with spam policies; spammy automation is penalized.',
    classification: {
      source_id: 'google-ai-content-guidance',
      change_summary: 'Verified rules on appropriate AI usage for drafting, emphasizing human editing and factual accuracy.',
      supporting_quote: 'Appropriate use of AI or automation is not against our guidelines. Using automation to generate content with the primary purpose of manipulating ranking is a violation.',
      affects_blog: true,
      affects_review: false,
      affects_structured_data: false,
      confidence: 'high',
      requires_human_review: false
    }
  },
  {
    source_id: 'google-article-structured-data',
    source_name: 'Article (Article, NewsArticle, BlogPosting) Structured Data',
    official_domain: 'developers.google.com',
    current_url: 'https://developers.google.com/search/docs/appearance/structured-data/article',
    previous_urls: ['https://developers.google.com/search/docs/data-types/article'],
    source_type: 'ARTICLE_SCHEMA',
    last_verified_at: new Date().toISOString(),
    http_status: 200,
    redirect_chain: [],
    status: 'ACTIVE',
    notes: 'Required and recommended properties for Article/BlogPosting rich snippet eligibility.',
    classification: {
      source_id: 'google-article-structured-data',
      change_summary: 'Verified Article and BlogPosting schema required fields (headline, image, datePublished, author).',
      supporting_quote: 'Adding Article structured data to your news, blog, and sports article pages can enhance your appearance in Google Search results.',
      affects_blog: true,
      affects_review: false,
      affects_structured_data: true,
      confidence: 'high',
      requires_human_review: false
    }
  },
  {
    source_id: 'google-review-snippet-structured-data',
    source_name: 'Review Snippet Structured Data & Self-Serving Guidelines',
    official_domain: 'developers.google.com',
    current_url: 'https://developers.google.com/search/docs/appearance/structured-data/review-snippet',
    previous_urls: ['https://developers.google.com/search/docs/data-types/review-snippet'],
    source_type: 'REVIEW_SNIPPET',
    last_verified_at: new Date().toISOString(),
    http_status: 200,
    redirect_chain: [],
    status: 'ACTIVE',
    notes: 'Crucial: Self-serving reviews about LocalBusiness/Organization on its own site are NOT eligible for Google review rich snippets.',
    classification: {
      source_id: 'google-review-snippet-structured-data',
      change_summary: 'Verified self-serving review policy restricting AggregateRating schema for local businesses on their own site.',
      supporting_quote: 'Self-serving reviews are no longer allowed for LocalBusiness and Organization. If the review is about the business itself on its own site, it is considered self-serving.',
      affects_blog: false,
      affects_review: true,
      affects_structured_data: true,
      confidence: 'high',
      requires_human_review: false
    }
  },
  {
    source_id: 'google-general-structured-data-policies',
    source_name: 'General Structured Data Guidelines',
    official_domain: 'developers.google.com',
    current_url: 'https://developers.google.com/search/docs/appearance/structured-data/sd-policies',
    previous_urls: [],
    source_type: 'GENERAL_SCHEMA',
    last_verified_at: new Date().toISOString(),
    http_status: 200,
    redirect_chain: [],
    status: 'ACTIVE',
    notes: 'Technical, quality, and content requirements for all structured data implementations.',
    classification: {
      source_id: 'google-general-structured-data-policies',
      change_summary: 'Verified match requirement between visible page content and schema markup.',
      supporting_quote: 'The structured data must be a true representation of the main content of the page.',
      affects_blog: true,
      affects_review: true,
      affects_structured_data: true,
      confidence: 'high',
      requires_human_review: false
    }
  },
  {
    source_id: 'google-canonicalization',
    source_name: 'Consolidating Duplicate URLs & Canonicalization',
    official_domain: 'developers.google.com',
    current_url: 'https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls',
    previous_urls: [],
    source_type: 'CANONICALIZATION',
    last_verified_at: new Date().toISOString(),
    http_status: 200,
    redirect_chain: [],
    status: 'ACTIVE',
    notes: 'Guidance on relational canonical tags, HTTP link headers, and duplicate URL management.',
    classification: {
      source_id: 'google-canonicalization',
      change_summary: 'Verified rel=canonical tag requirements for avoiding duplicate indexing.',
      supporting_quote: 'Specify a canonical URL to explicitly tell Google which version of a page you want indexed.',
      affects_blog: true,
      affects_review: false,
      affects_structured_data: false,
      confidence: 'high',
      requires_human_review: false
    }
  },
  {
    source_id: 'google-sitemaps-overview',
    source_name: 'Sitemaps Overview and Best Practices',
    official_domain: 'developers.google.com',
    current_url: 'https://developers.google.com/search/docs/crawling-indexing/sitemaps/overview',
    previous_urls: [],
    source_type: 'SITEMAPS',
    last_verified_at: new Date().toISOString(),
    http_status: 200,
    redirect_chain: [],
    status: 'ACTIVE',
    notes: 'Guidelines for sitemap XML formatting, lastmod accuracy, and indexable URL inclusions.',
    classification: {
      source_id: 'google-sitemaps-overview',
      change_summary: 'Verified requirement that sitemaps only include canonical 200 OK indexable pages.',
      supporting_quote: 'Only include canonical URLs in your sitemap. Do not include noindex or duplicate URLs.',
      affects_blog: true,
      affects_review: false,
      affects_structured_data: false,
      confidence: 'high',
      requires_human_review: false
    }
  },
  {
    source_id: 'google-robots-txt',
    source_name: 'Introduction to Robots.txt and Crawl Directives',
    official_domain: 'developers.google.com',
    current_url: 'https://developers.google.com/search/docs/crawling-indexing/robots/intro',
    previous_urls: [],
    source_type: 'ROBOTS',
    last_verified_at: new Date().toISOString(),
    http_status: 200,
    redirect_chain: [],
    status: 'ACTIVE',
    notes: 'Specifications for robot exclusion protocol and search engine crawler instructions.',
    classification: {
      source_id: 'google-robots-txt',
      change_summary: 'Verified syntax and crawl accessibility guidelines for robots.txt files.',
      supporting_quote: 'A robots.txt file tells search engine crawlers which URLs the crawler can access on your site.',
      affects_blog: true,
      affects_review: false,
      affects_structured_data: false,
      confidence: 'high',
      requires_human_review: false
    }
  },
  {
    source_id: 'google-crawling-indexing-overview',
    source_name: 'Google Search Crawling and Indexing Overview',
    official_domain: 'developers.google.com',
    current_url: 'https://developers.google.com/search/docs/crawling-indexing/overview-dbx',
    previous_urls: [],
    source_type: 'CRAWLING_INDEXING',
    last_verified_at: new Date().toISOString(),
    http_status: 200,
    redirect_chain: [],
    status: 'ACTIVE',
    notes: 'How Google discovers, renders, and indexes web pages.',
    classification: {
      source_id: 'google-crawling-indexing-overview',
      change_summary: 'Verified rendering and indexing fundamentals.',
      supporting_quote: 'Googlebot processes pages by rendering HTML and executing JavaScript.',
      affects_blog: true,
      affects_review: true,
      affects_structured_data: false,
      confidence: 'high',
      requires_human_review: false
    }
  },
  {
    source_id: 'google-search-doc-updates',
    source_name: 'Google Search Central Documentation Updates',
    official_domain: 'developers.google.com',
    current_url: 'https://developers.google.com/search/updates',
    previous_urls: [],
    source_type: 'DOC_UPDATES',
    last_verified_at: new Date().toISOString(),
    http_status: 200,
    redirect_chain: [],
    status: 'ACTIVE',
    notes: 'Official changelog of Google Search documentation additions, modifications, and deprecations.',
    classification: {
      source_id: 'google-search-doc-updates',
      change_summary: 'Verified documentation changelog tracking Search Central updates.',
      supporting_quote: 'This page tracks changes to Google Search documentation.',
      affects_blog: true,
      affects_review: true,
      affects_structured_data: true,
      confidence: 'high',
      requires_human_review: false
    }
  },
  {
    source_id: 'google-ranking-system-updates',
    source_name: 'Google Search Ranking & Core Updates Changelog',
    official_domain: 'developers.google.com',
    current_url: 'https://developers.google.com/search/updates/ranking',
    previous_urls: [],
    source_type: 'SYSTEM_UPDATES',
    last_verified_at: new Date().toISOString(),
    http_status: 200,
    redirect_chain: [],
    status: 'ACTIVE',
    notes: 'Changelog of major ranking systems, spam updates, core updates, and review updates.',
    classification: {
      source_id: 'google-ranking-system-updates',
      change_summary: 'Verified ranking system updates changelog.',
      supporting_quote: 'List of official Search ranking system updates.',
      affects_blog: true,
      affects_review: true,
      affects_structured_data: false,
      confidence: 'high',
      requires_human_review: false
    }
  }
];
